name: Sync All Sensors Codecs

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  sync-codecs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests PyGithub

      - name: Run Sync Script
        env:
          CODEC_TOKEN: ${{ secrets.CODEC_TOKEN }}
        run: python .github/scripts/sync_codecs.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.CODEC_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "Auto-sync all sensor codecs"
          git push origin main
