name: Sync Milesight Sensors

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-milesight-codecs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run Sync Script
        env:
          CODEC_TOKEN: ${{ secrets.CODEC_TOKEN }} # Reusing the same token
        run: python .github/scripts/sync_milesight_codecs.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.CODEC_TOKEN }} # Reusing the same token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "Sync Milesight sensors"
          git push origin main
